services:
  web:
    build:
      context: .
    volumes:
      - ./upload:/upload
    env_file:
      - ./upload/.env
    ports:
      - "8000:8000"
    command: >
      sh -c "python manage.py makemigrations &&
             python manage.py migrate &&
             python manage.py collectstatic --noinput &&
             gunicorn -w 5 -b 0.0.0.0:8000 upload.wsgi"

    depends_on:
      - database

  database:
    image: postgres:14.6-alpine
    volumes:
      - postgres-data:/var/lib/postgresql/data/
    env_file:
      - ./upload/.env

  redis:
    image: redis:7.0.5
    hostname: redis

  celery:
    build:
      context: .
    command: celery -A upload worker -l info
    volumes:
      - ./upload:/upload
    env_file:
      - ./upload/.env
    links:
      - redis
    depends_on:
      - redis
      - database

volumes:
  postgres-data: